test

diff --git a/git_hooks/pre-push b/git_hooks/pre-push
--- a/git_hooks/pre-push
+++ b/git_hooks/pre-push
@@ -1,43 +1,29 @@
-#!/bin/sh
+#!/bin/bash
 
-# Set the color variables
-yellow='\033[33m'
-red='\033[31m'
-green='\033[32m'
-reset='\033[0m'
+prompt_continue_with_errors() {
+  read -p "Do you want to continue with errors? (y/n) " -n 1 -r
+  echo ""
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+    exit 1
+  fi
+}
 
+# Run flutter analyze
+analysis_output=$(flutter analyze)
 
-# Run code analysis before committing
-echo "${red}pre-push: Running Dart Analyzer...${reset}"
-# Run flutter analyze and capture the exit status
-output_analyze=$(flutter analyze 2>&1)
-status_analyze=$?
-
-# Print the output of the analyze command
-echo "$output_analyze"
-
-# Exit with an error message if analysis fail
-if [ $status_analyze -ne 0 ]; then
-  echo "${red}pre-push: Some analysis failed. Aborting push.${reset}"
-  exit 1
-else
-    echo "${red}pre-push: ${green}Dart analyzer passed!, No issues found!${reset}"
+# If there are any issues, prompt the user to continue
+if [ $? -ne 0 ]; then
+  echo "flutter analyze found issues:"
+  echo "$analysis_output"
+  prompt_continue_with_errors
 fi
 
+# Run flutter test
+test_output=$(flutter test)
 
-
-# Run flutter test and capture the exit status
-echo "${red}pre-push: Running Flutter Tests...${reset}"
-output_test=$(flutter test 2>&1)
-status_test=$?
-
-# Print the output of the test command
-echo "$output_test"
-
-# Exit with an error message if any tests fail
-if [ $status_test -ne 0 ]; then
-  echo "${red}pre-push: Some tests failed. Aborting push.${reset}"
-  exit 1
-else
-    echo "${red}pre-push: ${green}All tests passed!${reset}"
+# If there are any failures, prompt the user to continue
+if [[ $test_output == *"Some tests failed"* ]]; then
+  echo "flutter test failed:"
+  echo "$test_output"
+  prompt_continue_with_errors
 fi
